### ISSUE TITLE
createsuperuser doesn't work

### ISSUE THREAD

**Issue by nickf12** [linkedweb/auth_system#9]
Hi,
I have cloned your project and seems there is an issue with your customization of the user model.
The django command 'createsuperuser' is not working, below the error faced:
(venv) PS C:\Users\niccolo\auth_system\auth_system\backend> py manage.py createsuperuser
Email: nicco@gmail.com
First name: Nicco
Last name: Gmail
Password: 
Password (again):
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\niccolo\auth_system\auth_system\backend\venv\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\niccolo\auth_system\auth_system\backend\venv\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\niccolo\auth_system\auth_system\backend\venv\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\niccolo\auth_system\auth_system\backend\venv\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "C:\Users\niccolo\auth_system\auth_system\backend\venv\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\niccolo\auth_system\auth_system\backend\venv\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 189, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
AttributeError: 'UserAccountManager' object has no attribute 'create_superuser'

**Comment by nickf12** [comment]
Hi,
To fix this issue you should override the create_superuser method, please add below code in UserAccountManager class:

```
class UserAccountManager(BaseUserManager):
   (...)    
  def create_superuser(self, email, password=None, **extra_fields):
          extra_fields.setdefault('is_staff', True)
          extra_fields.setdefault('is_superuser', True)
          if extra_fields.get('is_staff') is not True:
              raise ValueError('SuperUser must have is_staff=True')
          if extra_fields.get('is_superuser') is not True:
              raise ValueError('Superuser must have is_superuser=True.')   
          return self.create_user(email, password, **extra_fields)
```
